//go:build !copilot_inprocess

// Code generated by copilot-sdk bundler; DO NOT EDIT.

package embedded

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"io"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_1.0.80_linux_amd64.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_1.0.80_linux_amd64.license
var localEmbeddedCopilotCLILicense []byte

func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli:     cliReader(),
		License: localEmbeddedCopilotCLILicense,
		Version: "1.0.80",
		CliHash: mustDecodeBase64("LrtJHbi7utWPsRGjSz+SeY2kQ0GXblpgIbwTx+V66eY="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
