// Code generated by copilot-sdk bundler; DO NOT EDIT.

package embedded

import (
	"bytes"
	"io"
	"encoding/base64"
	_ "embed"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_1.0.46_linux_amd64.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_1.0.46_linux_amd64.license
var localEmbeddedCopilotCLILicense []byte


func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli: cliReader(),
		License: localEmbeddedCopilotCLILicense,
		Version: "1.0.46",
		CliHash: mustDecodeBase64("33io489H79UwthrdRzJduMOfDovDmIFxwBrNFLn4aXg="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
