//go:build copilot_inprocess

// Code generated by copilot-sdk bundler; DO NOT EDIT.

package embedded

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"io"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_1.0.85_linux_arm64.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_1.0.85_linux_arm64.license
var localEmbeddedCopilotCLILicense []byte

//go:embed zcopilotruntime_1.0.85_linux-arm64.so.zst
var localEmbeddedCopilotRuntimeLib []byte

//go:embed zcopilotruntimewrapper_1.0.85_linux-arm64_copilot-runtime.zst
var localEmbeddedCopilotRuntimeExecutable []byte

//go:embed zcopilotruntimeassets_1.0.85_linux-arm64.tgz
var localEmbeddedCopilotRuntimeAssets []byte

//go:embed zcopilot_1.0.85_linuxmusl_arm64.zst
var localEmbeddedCopilotCLILinuxMusl []byte

//go:embed zcopilotruntime_1.0.85_linuxmusl-arm64.so.zst
var localEmbeddedCopilotRuntimeLibLinuxMusl []byte

//go:embed zcopilotruntimewrapper_1.0.85_linuxmusl-arm64_copilot-runtime.zst
var localEmbeddedCopilotRuntimeExecutableLinuxMusl []byte

//go:embed zcopilotruntimeassets_1.0.85_linuxmusl-arm64.tgz
var localEmbeddedCopilotRuntimeAssetsLinuxMusl []byte

func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli:                            cliReader(),
		License:                        localEmbeddedCopilotCLILicense,
		Version:                        "1.0.85",
		CliHash:                        mustDecodeBase64("cR4ZFHhnJoPFGhLsdA5x7xxxmi1CCA6FdA7zPrfc/+o="),
		RuntimeLib:                     runtimeLibReader(),
		RuntimeLibHash:                 mustDecodeBase64("rbeV/iqSj1oKcO9+UfhI3b55ku0xfZuGWU29EAtI7AA="),
		RuntimeNode:                    runtimeLibReader(),
		RuntimeNodeHash:                mustDecodeBase64("rbeV/iqSj1oKcO9+UfhI3b55ku0xfZuGWU29EAtI7AA="),
		RuntimeExecutable:              runtimeExecutableReader(),
		RuntimeExecutableHash:          mustDecodeBase64("cR4ZFHhnJoPFGhLsdA5x7xxxmi1CCA6FdA7zPrfc/+o="),
		RuntimeAssets:                  bytes.NewReader(localEmbeddedCopilotRuntimeAssets),
		RuntimeAssetsHash:              mustDecodeBase64("mbjMJibzkVnAl92HewMv1N6ao8t3mUSk1BC+ENeqE0Q="),
		LinuxMuslCli:                   linuxMuslCLIReader(),
		LinuxMuslCliHash:               mustDecodeBase64("33H/6S0Oi0QSmB5JryvSd6YDly6UMVc4BF+5dJdxSzQ="),
		LinuxMuslRuntimeLib:            linuxMuslRuntimeLibReader(),
		LinuxMuslRuntimeLibHash:        mustDecodeBase64("iNcepemkQQUfbCHEAbPQi4x+MdMkFe8eNzct1MyYHA0="),
		LinuxMuslRuntimeNode:           linuxMuslRuntimeLibReader(),
		LinuxMuslRuntimeNodeHash:       mustDecodeBase64("iNcepemkQQUfbCHEAbPQi4x+MdMkFe8eNzct1MyYHA0="),
		LinuxMuslRuntimeExecutable:     linuxMuslRuntimeExecutableReader(),
		LinuxMuslRuntimeExecutableHash: mustDecodeBase64("33H/6S0Oi0QSmB5JryvSd6YDly6UMVc4BF+5dJdxSzQ="),
		LinuxMuslRuntimeAssets:         bytes.NewReader(localEmbeddedCopilotRuntimeAssetsLinuxMusl),
		LinuxMuslRuntimeAssetsHash:     mustDecodeBase64("latpuLBmjLI3EKcFj16ORKzPER4NUJBNE9HVzqfctPs="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeLibReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeLib))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeExecutableReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeExecutable))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func linuxMuslCLIReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLILinuxMusl))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func linuxMuslRuntimeLibReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeLibLinuxMusl))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func linuxMuslRuntimeExecutableReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeExecutableLinuxMusl))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
