//go:build !copilot_inprocess

// Code generated by copilot-sdk bundler; DO NOT EDIT.

package embedded

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"io"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_1.0.85_darwin_arm64.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_1.0.85_darwin_arm64.license
var localEmbeddedCopilotCLILicense []byte

//go:embed zcopilotruntime_1.0.85_darwin-arm64.dylib.zst
var localEmbeddedCopilotRuntimeLib []byte

//go:embed zcopilotruntimewrapper_1.0.85_darwin-arm64_copilot-runtime.zst
var localEmbeddedCopilotRuntimeExecutable []byte

//go:embed zcopilotruntimeassets_1.0.85_darwin-arm64.tgz
var localEmbeddedCopilotRuntimeAssets []byte

func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli:                   cliReader(),
		License:               localEmbeddedCopilotCLILicense,
		Version:               "1.0.85",
		CliHash:               mustDecodeBase64("Gnxv2MtC+BQwu2/sMvQGanKIaDCSmBwa5+TSYeU7yB0="),
		RuntimeLib:            runtimeLibReader(),
		RuntimeLibHash:        mustDecodeBase64("AcXsLC44xXKFgQb1vGKi0iNORqHfbQDti4cDjoRpPC0="),
		RuntimeNode:           runtimeLibReader(),
		RuntimeNodeHash:       mustDecodeBase64("AcXsLC44xXKFgQb1vGKi0iNORqHfbQDti4cDjoRpPC0="),
		RuntimeExecutable:     runtimeExecutableReader(),
		RuntimeExecutableHash: mustDecodeBase64("Gnxv2MtC+BQwu2/sMvQGanKIaDCSmBwa5+TSYeU7yB0="),
		RuntimeAssets:         bytes.NewReader(localEmbeddedCopilotRuntimeAssets),
		RuntimeAssetsHash:     mustDecodeBase64("0qQMD43i3Yleukh02dlbkX9AVYfqUFY7JqKMQ1LFzRc="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeLibReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeLib))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeExecutableReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeExecutable))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
