//go:build copilot_inprocess

// Code generated by copilot-sdk bundler; DO NOT EDIT.

package embedded

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"io"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_1.0.85_darwin_amd64.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_1.0.85_darwin_amd64.license
var localEmbeddedCopilotCLILicense []byte

//go:embed zcopilotruntime_1.0.85_darwin-x64.dylib.zst
var localEmbeddedCopilotRuntimeLib []byte

//go:embed zcopilotruntimewrapper_1.0.85_darwin-x64_copilot-runtime.zst
var localEmbeddedCopilotRuntimeExecutable []byte

//go:embed zcopilotruntimeassets_1.0.85_darwin-x64.tgz
var localEmbeddedCopilotRuntimeAssets []byte

func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli:                   cliReader(),
		License:               localEmbeddedCopilotCLILicense,
		Version:               "1.0.85",
		CliHash:               mustDecodeBase64("QDwV0d0BqK0xvyaKb2FdYq0osANxI/gmBOlifug9GD8="),
		RuntimeLib:            runtimeLibReader(),
		RuntimeLibHash:        mustDecodeBase64("/6dcKFFwelb1fJ3Cfc/qBO7Z5h6/on/aBAsu1CsjZtg="),
		RuntimeNode:           runtimeLibReader(),
		RuntimeNodeHash:       mustDecodeBase64("/6dcKFFwelb1fJ3Cfc/qBO7Z5h6/on/aBAsu1CsjZtg="),
		RuntimeExecutable:     runtimeExecutableReader(),
		RuntimeExecutableHash: mustDecodeBase64("QDwV0d0BqK0xvyaKb2FdYq0osANxI/gmBOlifug9GD8="),
		RuntimeAssets:         bytes.NewReader(localEmbeddedCopilotRuntimeAssets),
		RuntimeAssetsHash:     mustDecodeBase64("YHMktBow/DbrasCtOEVHO00hyGUOOZs0DpB1LF7GOPU="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeLibReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeLib))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeExecutableReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeExecutable))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
