//go:build copilot_inprocess

// Code generated by copilot-sdk bundler; DO NOT EDIT.

package embedded

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"io"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_1.0.85_windows_arm64.exe.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_1.0.85_windows_arm64.exe.license
var localEmbeddedCopilotCLILicense []byte

//go:embed zcopilotruntime_1.0.85_win32-arm64.dll.zst
var localEmbeddedCopilotRuntimeLib []byte

//go:embed zcopilotruntimewrapper_1.0.85_win32-arm64_copilot-runtime.exe.zst
var localEmbeddedCopilotRuntimeExecutable []byte

//go:embed zcopilotruntimeassets_1.0.85_win32-arm64.tgz
var localEmbeddedCopilotRuntimeAssets []byte

func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli:                   cliReader(),
		License:               localEmbeddedCopilotCLILicense,
		Version:               "1.0.85",
		CliHash:               mustDecodeBase64("XHl+vEHmcvM+WFAQgWH3jDJCWEoupervQ+FIgUnMTnY="),
		RuntimeLib:            runtimeLibReader(),
		RuntimeLibHash:        mustDecodeBase64("a1zfxhfr04Xgst3w4hUgG7H3kIwXiYBpcH+FtudjOPM="),
		RuntimeNode:           runtimeLibReader(),
		RuntimeNodeHash:       mustDecodeBase64("a1zfxhfr04Xgst3w4hUgG7H3kIwXiYBpcH+FtudjOPM="),
		RuntimeExecutable:     runtimeExecutableReader(),
		RuntimeExecutableHash: mustDecodeBase64("XHl+vEHmcvM+WFAQgWH3jDJCWEoupervQ+FIgUnMTnY="),
		RuntimeAssets:         bytes.NewReader(localEmbeddedCopilotRuntimeAssets),
		RuntimeAssetsHash:     mustDecodeBase64("28DHcphYDOW3a/9VusX6I1lBi5u+r1Qqfgr7r+EIovg="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeLibReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeLib))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeExecutableReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeExecutable))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
