//go:build copilot_inprocess

// Code generated by copilot-sdk bundler; DO NOT EDIT.

package embedded

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"io"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_1.0.85_linux_amd64.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_1.0.85_linux_amd64.license
var localEmbeddedCopilotCLILicense []byte

//go:embed zcopilotruntime_1.0.85_linux-x64.so.zst
var localEmbeddedCopilotRuntimeLib []byte

//go:embed zcopilotruntimewrapper_1.0.85_linux-x64_copilot-runtime.zst
var localEmbeddedCopilotRuntimeExecutable []byte

//go:embed zcopilotruntimeassets_1.0.85_linux-x64.tgz
var localEmbeddedCopilotRuntimeAssets []byte

//go:embed zcopilot_1.0.85_linuxmusl_amd64.zst
var localEmbeddedCopilotCLILinuxMusl []byte

//go:embed zcopilotruntime_1.0.85_linuxmusl-x64.so.zst
var localEmbeddedCopilotRuntimeLibLinuxMusl []byte

//go:embed zcopilotruntimewrapper_1.0.85_linuxmusl-x64_copilot-runtime.zst
var localEmbeddedCopilotRuntimeExecutableLinuxMusl []byte

//go:embed zcopilotruntimeassets_1.0.85_linuxmusl-x64.tgz
var localEmbeddedCopilotRuntimeAssetsLinuxMusl []byte

func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli:                            cliReader(),
		License:                        localEmbeddedCopilotCLILicense,
		Version:                        "1.0.85",
		CliHash:                        mustDecodeBase64("Dg6b3SCLPTP7E7Jo0IQ5BPu9cei2q04kj04kH6SY7L8="),
		RuntimeLib:                     runtimeLibReader(),
		RuntimeLibHash:                 mustDecodeBase64("cfBYLb9Vz3J83WzV5heYT8SQUCe7J8pbJnkoHoZQ31Q="),
		RuntimeNode:                    runtimeLibReader(),
		RuntimeNodeHash:                mustDecodeBase64("cfBYLb9Vz3J83WzV5heYT8SQUCe7J8pbJnkoHoZQ31Q="),
		RuntimeExecutable:              runtimeExecutableReader(),
		RuntimeExecutableHash:          mustDecodeBase64("Dg6b3SCLPTP7E7Jo0IQ5BPu9cei2q04kj04kH6SY7L8="),
		RuntimeAssets:                  bytes.NewReader(localEmbeddedCopilotRuntimeAssets),
		RuntimeAssetsHash:              mustDecodeBase64("0zmBYauFE+Xep6W8LwVboJ/sCjFmsvQ3SGTJ7Ck3Re0="),
		LinuxMuslCli:                   linuxMuslCLIReader(),
		LinuxMuslCliHash:               mustDecodeBase64("9MCJE3G+5ISzzKzHBpd+gUDNS01/5RXkRDCAESt8XDU="),
		LinuxMuslRuntimeLib:            linuxMuslRuntimeLibReader(),
		LinuxMuslRuntimeLibHash:        mustDecodeBase64("BWkfigsM6w5ieWo9pnJzQdErpnJBX78+nKWJP1gGOy0="),
		LinuxMuslRuntimeNode:           linuxMuslRuntimeLibReader(),
		LinuxMuslRuntimeNodeHash:       mustDecodeBase64("BWkfigsM6w5ieWo9pnJzQdErpnJBX78+nKWJP1gGOy0="),
		LinuxMuslRuntimeExecutable:     linuxMuslRuntimeExecutableReader(),
		LinuxMuslRuntimeExecutableHash: mustDecodeBase64("9MCJE3G+5ISzzKzHBpd+gUDNS01/5RXkRDCAESt8XDU="),
		LinuxMuslRuntimeAssets:         bytes.NewReader(localEmbeddedCopilotRuntimeAssetsLinuxMusl),
		LinuxMuslRuntimeAssetsHash:     mustDecodeBase64("07cIDzM5fsC+3PFwE4cvKvTGEY49vSNIr6EU2v9vG7A="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeLibReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeLib))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func runtimeExecutableReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeExecutable))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func linuxMuslCLIReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLILinuxMusl))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func linuxMuslRuntimeLibReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeLibLinuxMusl))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func linuxMuslRuntimeExecutableReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotRuntimeExecutableLinuxMusl))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
