// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

package registry

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gopkg.in/yaml.v3"
)

// LockfileName is the file name for the Waza module lockfile.
const LockfileName = "waza.lock"

// LockfileSchemaVersion is the current lockfile schema version.
const LockfileSchemaVersion = 1

// Lockfile is the on-disk representation of pinned module resolutions.
// See docs/research/waza-eval-registry-design.md §8.
type Lockfile struct {
	SchemaVersion int          `yaml:"schema_version"`
	Modules       []LockModule `yaml:"modules,omitempty"`
}

// LockModule pins one resolved ref to an immutable commit SHA and content digest.
type LockModule struct {
	// Ref is the canonical ref string exactly as it appears in eval.yaml
	// (e.g. "github.com/waza-evals/fact#factuality@v1.0.0").
	Ref string `yaml:"ref"`
	// Module is the module identity ("host/owner/repo").
	Module string `yaml:"module"`
	// Version is the human-friendly selector — a semver tag or the same
	// commit SHA as Commit when the ref pinned by SHA.
	Version string `yaml:"version"`
	// Commit is the resolved 40-char commit SHA. This is the reproducibility
	// guarantee: `waza run` verifies the cached module contents against this
	// SHA + Digest before loading.
	Commit string `yaml:"commit"`
	// Digest is the sha256 content digest of the resolved artifact (e.g. the
	// grader preset YAML file), in "sha256:<hex>" form.
	Digest string `yaml:"digest"`
	// URL is the resolved source URL used to fetch the artifact. Recorded
	// for auditability; not verified on read.
	URL string `yaml:"url,omitempty"`
	// ResolvedAt is when the lock entry was written.
	ResolvedAt time.Time `yaml:"resolved_at,omitempty"`
}

// LockfilePath returns the expected path of the lockfile beside the given
// eval.yaml path.
func LockfilePath(evalPath string) string {
	return filepath.Join(filepath.Dir(evalPath), LockfileName)
}

// LoadLockfile reads and parses a lockfile. It returns (nil, nil) when the
// file does not exist so callers can distinguish "no lock" from a parse error.
func LoadLockfile(path string) (*Lockfile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading lockfile %s: %w", path, err)
	}
	var lock Lockfile
	if err := yaml.Unmarshal(data, &lock); err != nil {
		return nil, fmt.Errorf("parsing lockfile %s: %w", path, err)
	}
	if lock.SchemaVersion == 0 {
		// Older/empty files: default to current schema for forward-compat.
		lock.SchemaVersion = LockfileSchemaVersion
	}
	if lock.SchemaVersion != LockfileSchemaVersion {
		return nil, fmt.Errorf("lockfile %s: unsupported schema_version %d (expected %d)", path, lock.SchemaVersion, LockfileSchemaVersion)
	}
	return &lock, nil
}

// Save writes the lockfile to disk with entries sorted by ref for stable diffs.
func (l *Lockfile) Save(path string) error {
	if l.SchemaVersion == 0 {
		l.SchemaVersion = LockfileSchemaVersion
	}
	sort.Slice(l.Modules, func(i, j int) bool {
		return l.Modules[i].Ref < l.Modules[j].Ref
	})
	data, err := yaml.Marshal(l)
	if err != nil {
		return fmt.Errorf("marshaling lockfile: %w", err)
	}
	// Prepend a small header comment so hand-inspection is obvious.
	header := []byte("# waza.lock — auto-generated by `waza get`. Do not edit by hand.\n# See docs/research/waza-eval-registry-design.md for the design.\n")
	if err := os.WriteFile(path, append(header, data...), 0o644); err != nil {
		return fmt.Errorf("writing lockfile %s: %w", path, err)
	}
	return nil
}

// Lookup returns the lock entry for the given ref string, or nil if absent.
func (l *Lockfile) Lookup(ref string) *LockModule {
	if l == nil {
		return nil
	}
	for i := range l.Modules {
		if l.Modules[i].Ref == ref {
			return &l.Modules[i]
		}
	}
	return nil
}

// Upsert inserts or replaces the entry for the given ref.
func (l *Lockfile) Upsert(m LockModule) {
	for i := range l.Modules {
		if l.Modules[i].Ref == m.Ref {
			l.Modules[i] = m
			return
		}
	}
	l.Modules = append(l.Modules, m)
}
